### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Sinansi** [StephenVavasis/Unroll.jl#5]
Hello,

How can I install this package?

I am using Julia 1.4 and I keep getting package not found error.

(@v1.4) pkg> add https://github.com/StephenVavasis/Unroll.jl
   Updating git-repo `https://github.com/StephenVavasis/Unroll.jl`
ERROR: could not find project file in package at https://github.com/StephenVavasis/Unroll.jl

**Comment by StephenVavasis** [comment]
I am not maintaining this package any more because I don't think it is useful.  Recent versions of Julia offer extensive constant propagation.

**Comment by Sinansi** [comment]
@StephenVavasis Thank you!
